[package]
name = "datum-connect"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
dotenv.workspace = true
lib.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true

clap = { version = "4.5.50", features = ["derive"] }
tracing.workspace = true
